# Generated by Django 4.2.30 on 2026-05-02 18:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("payments", "0001_initial"),
        ("rides", "0001_initial"),
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="ride",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="transactions",
                to="rides.ride",
            ),
        ),
        migrations.AddField(
            model_name="commission",
            name="convoyeur",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="commissions",
                to="accounts.convoyeurprofile",
            ),
        ),
        migrations.AddField(
            model_name="commission",
            name="transaction",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="commission",
                to="payments.transaction",
            ),
        ),
    ]
