# Generated by Django 4.2.30 on 2026-05-02 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="convoyeurprofile",
            old_name="account_number",
            new_name="numero_id",
        ),
        migrations.RemoveField(
            model_name="clientprofile", name="preferred_payment_method",
        ),
        migrations.RemoveField(model_name="clientprofile", name="total_rides",),
        migrations.RemoveField(model_name="clientprofile", name="total_spent",),
        migrations.RemoveField(model_name="convoyeurprofile", name="acceptance_rate",),
        migrations.RemoveField(
            model_name="convoyeurprofile", name="account_holder_name",
        ),
        migrations.RemoveField(model_name="convoyeurprofile", name="bank_name",),
        migrations.RemoveField(
            model_name="convoyeurprofile", name="cancellation_count",
        ),
        migrations.RemoveField(model_name="convoyeurprofile", name="completion_rate",),
        migrations.RemoveField(model_name="convoyeurprofile", name="created_at",),
        migrations.RemoveField(
            model_name="convoyeurprofile", name="mobile_money_number",
        ),
        migrations.RemoveField(model_name="convoyeurprofile", name="national_id",),
        migrations.RemoveField(model_name="convoyeurprofile", name="total_earnings",),
        migrations.RemoveField(model_name="convoyeurprofile", name="updated_at",),
        migrations.RemoveField(model_name="convoyeurprofile", name="vehicle_color",),
        migrations.RemoveField(
            model_name="convoyeurprofile", name="verification_notes",
        ),
        migrations.RemoveField(
            model_name="convoyeurprofile", name="years_of_experience",
        ),
        migrations.AlterField(
            model_name="convoyeurprofile",
            name="vehicle_type",
            field=models.CharField(
                choices=[
                    ("voiture", "Voiture"),
                    ("motorcycle", "Motorcycle"),
                    ("velo", "Velo"),
                ],
                default="motorcycle",
                max_length=20,
            ),
        ),
    ]
