# Generated by Django 4.2.30 on 2026-05-02 18:41

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Bid",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "proposed_price",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("estimated_arrival_minutes", models.IntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "En attente"),
                            ("accepted", "Acceptée"),
                            ("rejected", "Rejetée"),
                            ("expired", "Expirée"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "convoyeur",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bids",
                        to="accounts.convoyeurprofile",
                    ),
                ),
            ],
            options={"ordering": ["proposed_price"],},
        ),
        migrations.CreateModel(
            name="Ride",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "pickup_location",
                    django.contrib.gis.db.models.fields.PointField(srid=4326),
                ),
                ("pickup_address", models.CharField(max_length=255)),
                (
                    "dropoff_location",
                    django.contrib.gis.db.models.fields.PointField(srid=4326),
                ),
                ("dropoff_address", models.CharField(max_length=255)),
                ("distance_km", models.FloatField()),
                ("estimated_duration_minutes", models.IntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "En attente de offres"),
                            ("bidding", "Enchères en cours"),
                            ("accepted", "Offre acceptée"),
                            ("assigned", "Convoyeur assigné"),
                            ("in_progress", "Course en cours"),
                            ("completed", "Terminée"),
                            ("cancelled", "Annulée"),
                            ("disputed", "Litige"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField()),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "final_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "payment_status",
                    models.CharField(
                        choices=[
                            ("pending", "En attente"),
                            ("paid", "Payé"),
                            ("failed", "Échoué"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rides",
                        to="accounts.clientprofile",
                    ),
                ),
                (
                    "selected_bid",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="selected_ride",
                        to="rides.bid",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="bid",
            name="ride",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bids",
                to="rides.ride",
            ),
        ),
    ]
